program: raop_baselines.py
project: social_chatgpt
method: grid
metric:
  name: eval/acc
  goal: maximize
parameters:
  lr:
    values: [1e-5, 2e-5, 5e-5]
  epoch:
    values: [1, 2, 3]
  seed:
    values: [40, 41, 42]
